//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elektroniksecim_v0.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChainWithValid
    {
        public Nullable<bool> ValidWithPrev { get; set; }
        public long blockID { get; set; }
        public byte[] blockHash { get; set; }
        public long oyID { get; set; }
        public long prevBlockID { get; set; }
        public byte[] prevBlockHash { get; set; }
    }
}
