//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elektroniksecim_v0.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetBaslamisSecimler
    {
        public long secimID { get; set; }
        public string secimAdi { get; set; }
        public System.DateTimeOffset baslangicTarihi { get; set; }
        public System.DateTimeOffset bitisTarihi { get; set; }
        public Nullable<bool> iptalEdildi { get; set; }
        public Nullable<long> kazananAdayID { get; set; }
        public long durumTypeID { get; set; }
        public string durumTypeAciklama { get; set; }
    }
}
