//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elektroniksecim_v0.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class elektroniksecimEntities : DbContext
    {
        public elektroniksecimEntities()
            : base("name=elektroniksecimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aday> Aday { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Block> Block { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<KullaniciDurumType> KullaniciDurumType { get; set; }
        public virtual DbSet<OyIslemi> OyIslemi { get; set; }
        public virtual DbSet<Secim> Secim { get; set; }
        public virtual DbSet<SecimDurumType> SecimDurumType { get; set; }
        public virtual DbSet<SecmeHakki> SecmeHakki { get; set; }
        public virtual DbSet<Secmen> Secmen { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ChainWithValid> ChainWithValid { get; set; }
        public virtual DbSet<GetBaslamamisSecimler> GetBaslamamisSecimler { get; set; }
        public virtual DbSet<GetBaslamisSecimler> GetBaslamisSecimler { get; set; }
        public virtual DbSet<GetBitmisSecimler> GetBitmisSecimler { get; set; }
        public virtual DbSet<GetIptalEdilmisSecimler> GetIptalEdilmisSecimler { get; set; }
        public virtual DbSet<GetSecimWithEnCokOyAlanAday> GetSecimWithEnCokOyAlanAday { get; set; }
    
        [DbFunction("elektroniksecimEntities", "fn_testfonksiyon")]
        public virtual IQueryable<fn_testfonksiyon_Result> fn_testfonksiyon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_testfonksiyon_Result>("[elektroniksecimEntities].[fn_testfonksiyon]()");
        }
    
        [DbFunction("elektroniksecimEntities", "GetEnCokOyAlanAday")]
        public virtual IQueryable<GetEnCokOyAlanAday_Result> GetEnCokOyAlanAday(Nullable<long> secimID)
        {
            var secimIDParameter = secimID.HasValue ?
                new ObjectParameter("secimID", secimID) :
                new ObjectParameter("secimID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetEnCokOyAlanAday_Result>("[elektroniksecimEntities].[GetEnCokOyAlanAday](@secimID)", secimIDParameter);
        }
    
        [DbFunction("elektroniksecimEntities", "SecmeninOyKullanabilecegiSecimler")]
        public virtual IQueryable<SecmeninOyKullanabilecegiSecimler_Result> SecmeninOyKullanabilecegiSecimler(Nullable<long> secmenID)
        {
            var secmenIDParameter = secmenID.HasValue ?
                new ObjectParameter("secmenID", secmenID) :
                new ObjectParameter("secmenID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SecmeninOyKullanabilecegiSecimler_Result>("[elektroniksecimEntities].[SecmeninOyKullanabilecegiSecimler](@secmenID)", secmenIDParameter);
        }
    
        public virtual int AdayEkle(Nullable<long> secimID, string adayAdi)
        {
            var secimIDParameter = secimID.HasValue ?
                new ObjectParameter("secimID", secimID) :
                new ObjectParameter("secimID", typeof(long));
    
            var adayAdiParameter = adayAdi != null ?
                new ObjectParameter("adayAdi", adayAdi) :
                new ObjectParameter("adayAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdayEkle", secimIDParameter, adayAdiParameter);
        }
    
        public virtual int AdaySil(Nullable<long> secimID, Nullable<long> adayID)
        {
            var secimIDParameter = secimID.HasValue ?
                new ObjectParameter("secimID", secimID) :
                new ObjectParameter("secimID", typeof(long));
    
            var adayIDParameter = adayID.HasValue ?
                new ObjectParameter("adayID", adayID) :
                new ObjectParameter("adayID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaySil", secimIDParameter, adayIDParameter);
        }
    
        public virtual int AdminEkleWithID(Nullable<int> kullaniciID)
        {
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("kullaniciID", kullaniciID) :
                new ObjectParameter("kullaniciID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdminEkleWithID", kullaniciIDParameter);
        }
    
        public virtual int AdminEkleWithNickName(string kullaniciAdi)
        {
            var kullaniciAdiParameter = kullaniciAdi != null ?
                new ObjectParameter("kullaniciAdi", kullaniciAdi) :
                new ObjectParameter("kullaniciAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdminEkleWithNickName", kullaniciAdiParameter);
        }
    
        public virtual int KullaniciEkle(string kullaniciAdi, string parola, string adi, string soyadi, Nullable<short> durumTypeID)
        {
            var kullaniciAdiParameter = kullaniciAdi != null ?
                new ObjectParameter("kullaniciAdi", kullaniciAdi) :
                new ObjectParameter("kullaniciAdi", typeof(string));
    
            var parolaParameter = parola != null ?
                new ObjectParameter("parola", parola) :
                new ObjectParameter("parola", typeof(string));
    
            var adiParameter = adi != null ?
                new ObjectParameter("adi", adi) :
                new ObjectParameter("adi", typeof(string));
    
            var soyadiParameter = soyadi != null ?
                new ObjectParameter("soyadi", soyadi) :
                new ObjectParameter("soyadi", typeof(string));
    
            var durumTypeIDParameter = durumTypeID.HasValue ?
                new ObjectParameter("durumTypeID", durumTypeID) :
                new ObjectParameter("durumTypeID", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KullaniciEkle", kullaniciAdiParameter, parolaParameter, adiParameter, soyadiParameter, durumTypeIDParameter);
        }
    
        public virtual int OyKullan(Nullable<long> secimID, Nullable<long> secmenID, Nullable<long> adayID)
        {
            var secimIDParameter = secimID.HasValue ?
                new ObjectParameter("secimID", secimID) :
                new ObjectParameter("secimID", typeof(long));
    
            var secmenIDParameter = secmenID.HasValue ?
                new ObjectParameter("secmenID", secmenID) :
                new ObjectParameter("secmenID", typeof(long));
    
            var adayIDParameter = adayID.HasValue ?
                new ObjectParameter("adayID", adayID) :
                new ObjectParameter("adayID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OyKullan", secimIDParameter, secmenIDParameter, adayIDParameter);
        }
    
        public virtual int SecimIptalOlarakAyarla(Nullable<long> secimID)
        {
            var secimIDParameter = secimID.HasValue ?
                new ObjectParameter("secimID", secimID) :
                new ObjectParameter("secimID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SecimIptalOlarakAyarla", secimIDParameter);
        }
    
        public virtual int SecimIptalOlarakIsaretle(Nullable<long> secimID)
        {
            var secimIDParameter = secimID.HasValue ?
                new ObjectParameter("secimID", secimID) :
                new ObjectParameter("secimID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SecimIptalOlarakIsaretle", secimIDParameter);
        }
    
        public virtual int SecimOlustur(string secimAdi, Nullable<System.DateTimeOffset> baslangicTarihi, Nullable<System.DateTimeOffset> bitisTarihi)
        {
            var secimAdiParameter = secimAdi != null ?
                new ObjectParameter("secimAdi", secimAdi) :
                new ObjectParameter("secimAdi", typeof(string));
    
            var baslangicTarihiParameter = baslangicTarihi.HasValue ?
                new ObjectParameter("baslangicTarihi", baslangicTarihi) :
                new ObjectParameter("baslangicTarihi", typeof(System.DateTimeOffset));
    
            var bitisTarihiParameter = bitisTarihi.HasValue ?
                new ObjectParameter("bitisTarihi", bitisTarihi) :
                new ObjectParameter("bitisTarihi", typeof(System.DateTimeOffset));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SecimOlustur", secimAdiParameter, baslangicTarihiParameter, bitisTarihiParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int TumSecmenlereSecimHakkiTanimla(Nullable<long> secimID)
        {
            var secimIDParameter = secimID.HasValue ?
                new ObjectParameter("secimID", secimID) :
                new ObjectParameter("secimID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TumSecmenlereSecimHakkiTanimla", secimIDParameter);
        }
    
        public virtual int UpdateKazananAday(Nullable<long> secimID)
        {
            var secimIDParameter = secimID.HasValue ?
                new ObjectParameter("secimID", secimID) :
                new ObjectParameter("secimID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateKazananAday", secimIDParameter);
        }
    }
}
