//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elektroniksecim_v0.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Secim()
        {
            this.Aday = new HashSet<Aday>();
            this.OyIslemi = new HashSet<OyIslemi>();
            this.SecmeHakki = new HashSet<SecmeHakki>();
        }
    
        public long secimID { get; set; }
        public string secimAdi { get; set; }
        public System.DateTimeOffset baslangicTarihi { get; set; }
        public System.DateTimeOffset bitisTarihi { get; set; }
        public Nullable<bool> iptalEdildi { get; set; }
        public Nullable<long> kazananAdayID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aday> Aday { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OyIslemi> OyIslemi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecmeHakki> SecmeHakki { get; set; }
    }
}
