//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elektroniksecim_v0.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecmeHakki
    {
        public long secimID { get; set; }
        public long secmenID { get; set; }
        public bool oyHakki { get; set; }
    
        public virtual Secim Secim { get; set; }
        public virtual Secmen Secmen { get; set; }
    }
}
